import { createActions } from 'redux-actions';
import {
    ACCEPT_MAIN_TERMS,
    ACCEPT_PARTNER_TERMS,
    ADD_USER,
    ADD_USER_ERROR,
    CHECK_AML,
    DELETE_USER_BY_ID,
    DELETE_USER_BY_ID_ERROR,
    GET_ALL,
    GET_ALL_BY_ROLE,
    GET_ALL_BY_ROLE_ERROR,
    GET_ALL_ERROR,
    GET_ME,
    GET_ME_ERROR,
    GET_ME_PLAN,
    GET_PERMISSION,
    GET_PERMISSION_ERROR,
    GET_TOKEN,
    GET_TOKEN_ERROR,
    GET_USER,
    GET_USER_BY_ROLE,
    GET_USER_BY_ROLE_ERROR,
    GET_USER_ERROR,
    SET_AML,
    SET_ME,
    SET_PASSWORD,
    SET_PASSWORD_ERROR,
    SET_TOKEN,
    SET_TOKEN_ERROR,
    SET_USER,
    SET_USER_ERROR,
    TOKEN_EXPIRES,
    TOKEN_EXPIRES_ERROR,
    UPDATE_ME,
    UPDATE_ME_ERROR,
    UPDATE_PASSWORD,
    UPDATE_PASSWORD_ERROR,
    UPDATE_USER,
    UPDATE_USER_BY_ID,
    UPDATE_USER_BY_ID_ERROR,
    UPDATE_USER_ERROR,
    UPDATE_USER_IN_PLAN,
    UPDATE_USER_IN_PLAN_CASHFLOW,
    UPDATE_USER_IN_PLAN_ERROR,
    GET_RISK_PROFILE,
    GET_SCORE_RISK_PROFILE,
    ADD_RISK_PROFILE,
    ADD_RISK_PROFILE_ERROR, SET_FIRST_PASSWORD,
} from './types/UserTypes';

export const {
    addUser,
    addUserError,
    updateUserById,
    updateUserByIdError,
    deleteUserById,
    deleteUserByIdError,
    getUserByRole,
    getUserByRoleError,
    getUser,
    getUserError,
    setUser,
    setUserError,
    getMe,
    getMePlan,
    getMeError,
    updateMe,
    updateMeError,
    updateUser,
    updateUserError,
    updateUserInPlan,
    updateUserInPlanError,
    updateUserInPlanCashflow,
    getAll,
    getAllError,
    getAllByRole,
    getAllByRoleError,
    setPassword,
    setFirstPassword,
    setPasswordError,
    updatePassword,
    updatePasswordError,
    getPermission,
    getPermissionError,
    getToken,
    getTokenError,
    setToken,
    acceptMainTerms,
    acceptPartnerTerms,
    setTokenError,
    tokenExpires,
    tokenExpiresError,
    checkAml,
    getRiskProfile,
    getScoreRiskProfile,
    addRiskProfile,
    addRiskProfileError,
} = createActions({
    // Create new user
    [ADD_USER]: payload => payload,
    [ADD_USER_ERROR]: payload => payload,
    [UPDATE_USER_BY_ID]: payload => payload,
    [UPDATE_USER_BY_ID_ERROR]: payload => payload,
    [DELETE_USER_BY_ID]: payload => payload,
    [DELETE_USER_BY_ID_ERROR]: payload => payload,
    // Getting user
    [GET_USER_BY_ROLE]: payload => payload,
    [GET_USER_BY_ROLE_ERROR]: payload => payload,
    [GET_USER]: payload => payload,
    [GET_USER_ERROR]: payload => payload,
    // Setting user
    [SET_USER]: payload => payload,
    [SET_USER_ERROR]: payload => payload,
    // Getting me
    [GET_ME]: payload => payload,
    [GET_ME_PLAN]: payload => payload,
    [GET_ME_ERROR]: payload => payload,
    // Updating users
    [UPDATE_ME]: payload => payload,
    [UPDATE_ME_ERROR]: payload => payload,
    [UPDATE_USER]: payload => payload,
    [UPDATE_USER_ERROR]: payload => payload,
    [UPDATE_USER_IN_PLAN]: payload => payload,
    [UPDATE_USER_IN_PLAN_ERROR]: payload => payload,
    [UPDATE_USER_IN_PLAN_CASHFLOW]: payload => payload,
    // Getting all
    [GET_ALL]: payload => payload,
    [GET_ALL_ERROR]: payload => payload,
    [GET_ALL_BY_ROLE]: payload => payload,
    [GET_ALL_BY_ROLE_ERROR]: payload => payload,
    // Setting password
    [SET_PASSWORD]: payload => payload,
    [SET_FIRST_PASSWORD]: payload => payload,
    [SET_PASSWORD_ERROR]: payload => payload,
    // Updating password
    [UPDATE_PASSWORD]: payload => payload,
    [UPDATE_PASSWORD_ERROR]: payload => payload,
    // Getting permission
    [GET_PERMISSION]: payload => payload,
    [GET_PERMISSION_ERROR]: payload => payload,
    // Getting token
    [GET_TOKEN]: payload => payload,
    [GET_TOKEN_ERROR]: payload => payload,
    // Setting token
    [SET_TOKEN]: payload => payload,
    [SET_TOKEN_ERROR]: payload => payload,
    // Token expires
    [TOKEN_EXPIRES]: payload => payload,
    [TOKEN_EXPIRES_ERROR]: payload => payload,
    // Accept terms
    [ACCEPT_MAIN_TERMS]: payload => payload,
    [ACCEPT_PARTNER_TERMS]: payload => payload,
    // Setting me
    [SET_ME]: payload => payload,
    [SET_AML]: payload => payload,
    [CHECK_AML]: payload => payload,
    // RISK PROFILE
    [GET_RISK_PROFILE]: payload => payload,
    [GET_SCORE_RISK_PROFILE]: payload => payload,
    [ADD_RISK_PROFILE]: payload => payload,
    [ADD_RISK_PROFILE_ERROR]: payload => payload,
});
