/**
 * Common actions
 *
 */
export const SPINNER_ON = 'SPINNER_ON';
export const SPINNER_OFF = 'SPINNER_OFF';

export const REQUEST_RECEIVED_ERROR = 'REQUEST_RECEIVED_ERROR';
export const REQUEST_RECEIVED_DONE = 'REQUEST_RECEIVED_DONE';
export const LOCAL_REQUEST_RECEIVED_DONE = 'LOCAL_REQUEST_RECEIVED_DONE';
export const REQUESTS_RESET = 'REQUESTS_RESET';

export const CHECK_ACCESS = 'CHECK_ACCESS';

export const DEFERRED_REDIRECT = 'DEFERRED_REDIRECT';

export const LOCAL_ID = 'LOCAL_ID';
export const SET_REQUEST_WEBAPP = 'SET_REQUEST_WEBAPP';
