/**
 * User actions
 *
 */
export const ICON_SAVE = 'ICON_SAVE';
export const ICON_LOAD = 'ICON_LOAD';
export const FIRST_SAVE_WEBAPP = 'FIRST_SAVE_WEBAPP';
export const LOAD_PLAN_WEBAPP = 'LOAD_PLAN_WEBAPP';
export const SAVE_SLIDES_WEBAPP = 'SAVE_SLIDES_WEBAPP';
export const RELOAD_DEFAULT_WEBAPP = 'RELOAD_DEFAULT_WEBAPP';
export const SEARCH_CLIENT_WEBAPP = 'SEARCH_CLIENT_WEBAPP';
export const LOGIN_WEBAPP = 'LOGIN_WEBAPP';
export const LOAD_NEW_PLAN_WEBAPP = 'LOAD_NEW_PLAN_WEBAPP';
export const SET_PLAN_WEBAPP = 'SET_PLAN_WEBAPP';
export const LOAD_PRESENTAION_WEBAPP = 'LOAD_PRESENTAION_WEBAPP';

export const SAVE_PLAN = 'SAVE_PLAN';

export const SAVE_ICON = 'SAVE_ICON';

export const RELOAD_PAGE = 'RELOAD_PAGE';

export const MODAL_INFO = 'MODAL_INFO';
